package com.elite.gemini.chatbot.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF6366F1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE8E8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF1A1D4E)
val md_theme_light_secondary = Color(0xFF0EA5E9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4EDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F2C)
val md_theme_light_tertiary = Color(0xFF8B5CF6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF1E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1A4E)
val md_theme_light_error = Color(0xFFEF4444)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FAFC)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1E293B)
val md_theme_light_surfaceVariant = Color(0xFFE2E8F0)
val md_theme_light_onSurfaceVariant = Color(0xFF475569)
val md_theme_light_outline = Color(0xFF94A3B8)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF818CF8)
val md_theme_dark_onPrimary = Color(0xFF312E81)
val md_theme_dark_primaryContainer = Color(0xFF4F46E5)
val md_theme_dark_onPrimaryContainer = Color(0xFFE8E8FF)
val md_theme_dark_secondary = Color(0xFF38BDF8)
val md_theme_dark_onSecondary = Color(0xFF0C4A6E)
val md_theme_dark_secondaryContainer = Color(0xFF0EA5E9)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4EDFF)
val md_theme_dark_tertiary = Color(0xFFA78BFA)
val md_theme_dark_onTertiary = Color(0xFF3C1E70)
val md_theme_dark_tertiaryContainer = Color(0xFF6D28D9)
val md_theme_dark_onTertiaryContainer = Color(0xFFF1E7FF)
val md_theme_dark_error = Color(0xFFF87171)
val md_theme_dark_errorContainer = Color(0xFF991B1B)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0F172A)
val md_theme_dark_onBackground = Color(0xFFF8FAFC)
val md_theme_dark_surface = Color(0xFF1E293B)
val md_theme_dark_onSurface = Color(0xFFE2E8F0)
val md_theme_dark_surfaceVariant = Color(0xFF334155)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBD5E1)
val md_theme_dark_outline = Color(0xFF64748B)

// Chat Specific Colors
val userMessageGradientStart = Color(0xFF6366F1)
val userMessageGradientEnd = Color(0xFF8B5CF6)
val aiMessageBackground = Color(0xFF334155)
val inputBackground = Color(0xFF1E293B)
val shimmerBase = Color(0xFF334155)
val shimmerHighlight = Color(0xFF475569)
